name: "gemma_v2tt"
backend: "python"
max_batch_size: 0

input [
  {
    name: "AUDIO_BYTES"
    data_type: TYPE_STRING
    dims: [ 1 ]
  },
  {
    name: "TARGET_LANGUAGE"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

output [
  {
    name: "SEGMENTS_JSON"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

instance_group [
  {
    kind: KIND_GPU
    count: 1
    gpus: [1]
  }
]
